version: '3.8'

services:
  app:
    image: demo-app          # 도커 빌드 후 태그 이름
    build:
      context: .             # 현재 폴더 기준 Dockerfile 빌드
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"